### ISSUE TITLE
Remove "organized by TPG" text

### ISSUE THREAD

**Issue by LJWatson** [inclusivedesign24/inclusivedesign24.org#2]
Noticed that pages like the presenter's info, still have "organized by TPG" at the top of the content. Need to go through and remove these.

**Comment by patrickhlauke** [comment]
i think i expunged all those references in the updated version https://redesign--vigilant-morse-657bbe.netlify.com/2018/presenters/

**Comment by LJWatson** [comment]
It is still in the footer by the looks of things. "Supported by The 
Paciello Group and Barclays Access".
