### ISSUE TITLE
Heading structure is broken

### ISSUE THREAD

**Issue by LJWatson** [inclusivedesign24/inclusivedesign24.org#6]
On the [homepage](https://redesign--vigilant-morse-657bbe.netlify.com/2018/) the heading structure is wonky...

* h2 = "Save the date... #id24 returns on 11 October 2018!"
* h1 = "Tweets by @id24conf"
* h2 = "Inclusive Design 24 (#id24)
* h2 = "How to join"

**Comment by patrickhlauke** [comment]
also wonky on the schedule (as this originally was all under the main single-page, where ID24 was the `<h1>`). need to address, but being careful to also adapt all styles (which currently target/rely on heading sizes). on it...
