### ISSUE TITLE
Change "Supporters" in nav

### ISSUE THREAD

**Issue by LJWatson** [inclusivedesign24/inclusivedesign24.org#7]
We have "Supporters" in the nav. We offer two tiers of sponsorship, "Partners" and "Supporters", so we'll need to represent this somehow in the navigation. Complicated somewhat by the fact we only have Partners now, but no Supporters.

**Comment by patrickhlauke** [comment]
i'd hate to have "Partners/supporters" there...feels awkward. i suppose we can't lump both together (in the nav) as "Sponsors" ?

**Comment by patrickhlauke** [comment]
from skype chat, an oddball suggestion perhaps: "or...we change our distinction - rather than partners vs supporters, they're all supporters ... (especially if we don't get any actual "supporters" this time around and we only have "partners")"
