### ISSUE TITLE
Navigation labels are too verbose

### ISSUE THREAD

**Issue by LJWatson** [inclusivedesign24/inclusivedesign24.org#8]
The label for the main and secondary navigation blocks include the word "navigation". This isn't needed because that info is picked up from the ```<nav>``` element itself. Suggest changing the labels to "Main" and "Secondary" respectively.

**Comment by patrickhlauke** [comment]
fixed in https://github.com/inclusivedesign24/inclusivedesign24.org/commit/b946d9c088629c6a1b397d3fb0cb2cae2f99f94d
