### ISSUE TITLE
Change Partners/Supporters?

### ISSUE THREAD

**Issue by LJWatson** [inclusivedesign24/inclusivedesign24.org#9]
Could we change "Partners/Supporters" to "Partners & Supporters" perhaps?

**Comment by patrickhlauke** [comment]
subjectively, it looks odd (visually) using the ampersand, and replacing it with the word "and" makes it less obvious (again, visually) that it's a single item since the nav is horizontal.

counter-suggestion, assuming it's for SR output: slapping an aria-label in there instead?

**Comment by LJWatson** [comment]
It wasn't a s/reader thing, so much as it's different from the title of the resulting page. It's the same with "#id24u" and "#id24u events".

**Comment by patrickhlauke** [comment]
ah gotcha. yeah, this is where i've taken the liberty of slightly shortening/condensing the navigation item compared to the `<h1>` of the actual page, mainly for space/aesthetic considerations. happy to match the `<h1>`s if necessary instead

**Comment by LJWatson** [comment]
It'll still tweak my OCD for such things, but sounds like a good solution :)It'll still get my OCD, but go for it :)

**Comment by patrickhlauke** [comment]
Closed in https://github.com/inclusivedesign24/inclusivedesign24.org/commit/f798e335f411ba1b1add63132cec2e286949e474
